# Generated by Django 5.1 on 2026-06-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('lat', models.FloatField(db_index=True)),
                ('lng', models.FloatField(db_index=True)),
                ('price_per_gallon', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='api_fuelsta_lat_eb8e60_idx')],
            },
        ),
    ]
